# Generated by Django 2.1.2 on 2018-10-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waggon', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('line_type', models.CharField(choices=[('s', 'S-Bahn'), ('u', 'U-Bahn')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lines', models.ManyToManyField(to='UmsteigenApp.Line')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmsteigenApp.Line'),
        ),
        migrations.AddField(
            model_name='change',
            name='at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UmsteigenApp.Station'),
        ),
        migrations.AddField(
            model_name='change',
            name='from_direction',
            field=models.ManyToManyField(related_name='from_direction', to='UmsteigenApp.Direction'),
        ),
        migrations.AddField(
            model_name='change',
            name='to_direction',
            field=models.ManyToManyField(related_name='to_direction', to='UmsteigenApp.Direction'),
        ),
    ]
