# Generated by Django 2.1.2 on 2018-10-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['at']},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='line',
            name='end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='UmsteigenApp.Direction'),
        ),
        migrations.AddField(
            model_name='line',
            name='start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='UmsteigenApp.Direction'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UmsteigenApp.Line'),
        ),
    ]
