# Generated by Django 2.1.2 on 2018-10-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0002_auto_20181008_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='waggon',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hinten'), (2, 'hinteres Drittel'), (3, 'mitte'), (4, 'vorderes Drittel'), (5, 'vorne'), (6, 'vorderes oder hinteres Drittel'), (7, 'egal'), (8, 'vorne oder hinten'), (9, 'vorderes Drittel oder mitte oder hinteres Drittel')]),
        ),
    ]
