# Generated by Django 2.1.2 on 2018-10-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0003_auto_20181010_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='direction',
            new_name='name',
        ),
    ]
