# Generated by Django 2.1.2 on 2018-10-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0004_auto_20181011_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['line_type', 'number']},
        ),
        migrations.AddField(
            model_name='change',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='change',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='change',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
