# Generated by Django 2.1.2 on 2018-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0005_auto_20181016_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['line', 'name']},
        ),
        migrations.AddField(
            model_name='station',
            name='bvg_details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='bvg_pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
