# Generated by Django 2.1.2 on 2018-10-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0006_auto_20181021_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='bvg_details',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='bvg_pic',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
