# Generated by Django 2.1.8 on 2022-03-12 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0008_auto_20181021_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='change',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
