# Generated by Django 2.1.8 on 2022-03-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0009_auto_20220312_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
