# Generated by Django 2.1.8 on 2023-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0010_station_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='change_station',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='change',
            name='waggon',
            field=models.PositiveSmallIntegerField(choices=[(1, 'hinten'), (2, 'hinteres Drittel'), (3, 'mitte'), (4, 'vorderes Drittel'), (5, 'vorne'), (6, 'vorderes oder hinteres Drittel'), (7, 'egal'), (8, 'vorne oder hinten'), (9, 'vorderes Drittel oder mitte oder hinteres Drittel'), (10, 'vorderes Drittel oder vorne'), (11, 'hinteres Drittel oder hinten')]),
        ),
    ]
