# Generated by Django 2.1.8 on 2023-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0011_auto_20231128_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='sequence_available',
            field=models.BooleanField(default=False),
        ),
    ]
