# Generated by Django 2.1.8 on 2023-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0012_line_sequence_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='sequence',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
