# Generated by Django 2.1.8 on 2023-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0013_station_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sequence',
            field=models.BigIntegerField(),
        ),
    ]
