# Generated by Django 2.1.8 on 2023-11-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0014_auto_20231128_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='change_station',
            field=models.BooleanField(default=False),
        ),
    ]
