# Generated by Django 2.1.8 on 2023-12-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0015_auto_20231128_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='schema_pic',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='url_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
