# Generated by Django 2.1.8 on 2023-12-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0016_auto_20231219_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationOnLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.SmallIntegerField(blank=True, null=True)),
                ('liine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UmsteigenApp.Line')),
                ('staation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UmsteigenApp.Station')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='liness',
            field=models.ManyToManyField(related_name='liness', through='UmsteigenApp.StationOnLine', to='UmsteigenApp.Line'),
        ),
    ]
