# Generated by Django 2.1.8 on 2023-12-26 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0017_auto_20231226_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationonline',
            name='liine',
        ),
        migrations.RemoveField(
            model_name='stationonline',
            name='staation',
        ),
        migrations.RemoveField(
            model_name='station',
            name='liness',
        ),
        migrations.DeleteModel(
            name='StationOnLine',
        ),
    ]
