# Generated by Django 2.1.8 on 2023-12-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0018_auto_20231226_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
