# Generated by Django 2.1.8 on 2024-01-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0019_line_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='station',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
