# Generated by Django 2.1.8 on 2024-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UmsteigenApp', '0020_auto_20240105_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='db_station_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
