# Generated by Django 5.2.5 on 2025-08-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UmsteigenApp", "0021_station_db_station_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="line_type",
            field=models.CharField(
                choices=[("s", "S-Tog"), ("m", "Metro")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="number",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="station",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
